before_script:
  - "sh -e /etc/init.d/xvfb start"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script: "cd auth; bundle exec rake test_app; bundle exec rspec spec/controllers/admin/admin_users_controller_spec.rb"
notifications:
  email:
    - ryan@spreecommerce.com
  irc: "irc.freenode.org#spree"
branches:
  only:
    - 1-0-stable
    - master
rvm:
  - 1.8.7
  - 1.9.3
